[package]
name = "highway-hero"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.25"
ggez = "0.6"
rand = "0.8.5"
wgpu = "0.17"